### ISSUE TITLE
Bug in px routine. Temperature conversion failure

### ISSUE THREAD

**Issue by kakko3** [thermalogic/RustSEUIF97#1]
I found out a bug in seuif97::px call in case of temperature output. Following test fails as temperature is -121 which probably means that there is sign error while converting Kelvin to Celcius. Could be the same for function with temperature output but haven't tested.
```
#[test]
fn test_px(){
    let pressure = 0.5;  // 5 bar(a)
    let quality = 0.5;
    let temperature = seuif97::px(pressure, quality, seuif97::OT);
    assert!((temperature - 151.8362).abs() < 0.01, "{}", temperature)  // within 0.01 C
}
```

**Comment by thermalogic** [comment]
Thanks

Please test the modified code again.
