### ISSUE TITLE
Bug in px routine. Density does not work

### ISSUE THREAD

**Issue by kakko3** [thermalogic/RustSEUIF97#2]
Density calculation in saturated state does not work as expected. In fact it seems that there is some error state as the return value is -1000. Following test fail:

```
#[test]
fn test_px_density() {
    let pressure = 0.5; // 5 bar(a)
    let quality = 0.5;
    let density = seuif97::px(pressure, quality, seuif97::OD);
    let result= 915.284 * (1.0 - quality) + quality * 2.668058;
    assert!((density - result).abs() < 0.1, "{}", density) // within 0.1 kg/m3
}
```

**Comment by kakko3** [comment]
Seems like ph in saturated state also fails but tx works with density

**Comment by thermalogic** [comment]
Thanks

Please test the modified code again.

**Comment by kakko3** [comment]
Thanks! And sorry for the late reply. Have had other things going on for this week.

This might as well been my misunderstanding. Will post new issue
