### ISSUE TITLE
Units in front page do not match the the internal units of the px routine

### ISSUE THREAD

**Issue by kakko3** [thermalogic/RustSEUIF97#3]
In github frontpage pressure unit is said to be MPa, However, only the test below passes. Meaning that the unit is actually Pa! Did not occur to me before. There was something funky going on with temperatures with possible Celcius/Kelvin conversion bug before but I have to find it first.

``` rust
    #[test]
    fn test_px_sat_vap() {
        let pressure = 5e5;  // This is in Pascals not MPa
        let quality = 1.0;
        let density = px(pressure, quality, Variable::Density);
        let result = 915.284 * (1.0 - quality) + quality * 2.668058;
        assert!((density - result).abs() < 0.1, "{}", density) // within 0.1 kg/m3
    }
```

Just to my knowledge is the meaning to use the github frontpage unit system or SI base system. Typically I prefer SI base but anything is fine as either way I write thin wrappers over pretty much every external package.

**Comment by kakko3** [comment]
Also please check, below MPa are used instead.

``` rust
#[test]
fn test_ph_sat_density() {
    let pressure = 2.0;  // 2 MPa = 20 bar
    let temperature = 500.0;  // 500 C
    let enthalpy = seuif97::pt(pressure, temperature, seuif97::OH);
    let result = 3468.093;  // kJ/kg
    assert!((enthalpy - result).abs() < 0.1, "{}", enthalpy) // within 0.1 kJ/kg
}
```

In general, I think that the unit conversions are currently a big problem in this crate.  It is very hard to expect what to input and where. I don't know what is the original unit system in the paper but would it reasonable to stick to that instead of conversions? 

I usually try to do everything internally as SI base and have some kind of unit system implementation which user can inject into the tools at hand. Meaning that if user wants F, BTUs and whatnot it should be relatively easy to just throw the unit system as 4th argument to those functions?

**Comment by thermalogic** [comment]
Pressure  MPa
Temperature  °C
   
 p = 5e5; 
    x = 1.0;
    then, the output d=`-9999.0` indicates that the input parameter is an unreasonable value

   p = 0.5; // MPa
   x = 1.0;
  the output d=2.668058

**Comment by kakko3** [comment]
Ok sorry I said anything about this. I already got mixed with my own implementations in testing :D. You are totally correct in the above response. Thank you for your effort! This is resolved and so is my misunderstanding.
